version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "game_server.asgi:application"]
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8001:8001"
    depends_on:
      - backend