# Generated by Django 5.1.1 on 2024-10-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1_id", models.CharField(max_length=255)),
                ("player2_id", models.CharField(max_length=255)),
                ("player1_score", models.IntegerField(default=0)),
                ("player2_score", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
